
title: Disk Entrega Sorocaba
description: ""

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diskentregasorocaba.com.br/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript