
title: Disk Entrega Sorocaba
description: >
  Todos os serviços de entrega em um só lugar! Delivery na palma da sua mão, em qualquer parte da cidade.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diskentregasorocaba.com.br/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript

defaults:
  -
    scope:
      path: ""
      type: categorias
    values:
      layout: categoria
  -
    scope:
      path: ""
      type: parceiros
    values:
      layout: parceiro

collections:
  categorias:
    output: true
    permalink: /:path/
  parceiros:
    output: true
    permalink: /:path/
